/**
 * MFE Bootstrap
 *
 * Registers MFE domains, extensions, and handlers with the FrontX app.
 * Initial screen mounting is owned by ExtensionDomainSlot once its container
 * ref is attached.
 * This file is imported in main.tsx to wire MFE capabilities into the host app.
 *
 * MFE manifests are auto-generated by `npm run generate:mfe-manifests`
 * into ./generated-mfe-manifests. Run that script after adding or removing
 * MFE packages from src/mfe_packages/.
 */

import type { RefObject } from 'react';
import type { QueryClient } from '@tanstack/react-query';
import type { HAI3App, JSONSchema, MfeEntry, Extension, ScreenExtension } from '@cyberfabric/react';
import { bootstrapMfeDomains } from '@cyberfabric/react';
import { MFE_MANIFESTS } from './generated-mfe-manifests';

interface MfeManifestConfig {
  manifest: JSONSchema;
  entries: MfeEntry[];
  extensions: Extension[];
}

function isScreenExtension(extension: Extension): extension is ScreenExtension {
  const candidate = extension as { presentation?: { route?: string } };
  return typeof candidate.presentation?.route === 'string';
}

/**
 * Bootstrap MFE system for the host application.
 * Registers domains, extensions, and shared properties.
 * Initial screen mount is deferred to MfeScreenContainer -> ExtensionDomainSlot.
 *
 * @param app - FrontX application instance
 * @param screenContainerRef - React ref for the screen domain container element
 * @param queryClient - optional host-owned QueryClient for shared cache across MFE roots
 * @returns Array of registered screen extensions, for URL routing in MfeScreenContainer
 */
export async function bootstrapMFE(
  app: HAI3App,
  screenContainerRef: RefObject<HTMLDivElement | null>,
  queryClient?: QueryClient,
): Promise<ScreenExtension[]> {
  const screensetsRegistry = await bootstrapMfeDomains(app, screenContainerRef, queryClient);

  if (MFE_MANIFESTS.length === 0) {
    console.warn('[MFE Bootstrap] No MFE manifests found. Run `npm run generate:mfe-manifests` to generate them.');
    return [];
  }

  const manifests = MFE_MANIFESTS as MfeManifestConfig[];
  const screenExtensions: ScreenExtension[] = [];

  for (const config of manifests) {
    screensetsRegistry.typeSystem.register(config.manifest);

    for (const entry of config.entries) {
      screensetsRegistry.typeSystem.register({ ...entry, manifest: config.manifest });
    }

    for (const extension of config.extensions) {
      await screensetsRegistry.registerExtension(extension);
    }

    screenExtensions.push(...config.extensions.filter(isScreenExtension));
  }

  if (screenExtensions.length === 0) {
    console.warn('[MFE Bootstrap] No screen extensions available, skipping mount');
    return [];
  }

  return screenExtensions;
}
