blank_issues_enabled: false
contact_links:
  - name: Discussion Forum
    url: https://github.com/Cyber Fabric/FrontX/discussions
    about: Ask questions and share ideas in our discussion forum
  - name: Check Existing Issues
    url: https://github.com/Cyber Fabric/FrontX/issues
    about: Search for similar issues before creating a new one
