#!/usr/bin/env node

import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

// Generate MFE manifests registry
// Generates src/app/mfe/generated-mfe-manifests.ts from all mfe.json files
// found in src/mfe_packages/*/mfe.json

const MFE_PACKAGES_DIR = join(process.cwd(), 'src/mfe_packages');
const OUTPUT_DIR = join(process.cwd(), 'src/app/mfe');
const OUTPUT_FILE = join(OUTPUT_DIR, 'generated-mfe-manifests.ts');

function generateManifestRegistry(): void {
  try {
    // Ensure output directory exists
    if (!existsSync(OUTPUT_DIR)) {
      mkdirSync(OUTPUT_DIR, { recursive: true });
    }

    // Handle missing mfe_packages directory (new project, no MFEs yet)
    if (!existsSync(MFE_PACKAGES_DIR)) {
      console.log('ℹ️  No src/mfe_packages/ directory found. Generating empty registry.');
      writeFileSync(OUTPUT_FILE, emptyRegistry());
      console.log(`\n✅ Generated ${OUTPUT_FILE}`);
      return;
    }

    // Packages to exclude (templates, blanks, shared libraries)
    const EXCLUDED_PACKAGES = new Set(['_blank-mfe', 'shared', '.git', '.DS_Store']);

    // Find all MFE packages
    const mfePackages = readdirSync(MFE_PACKAGES_DIR).filter((dir) => {
      // Skip excluded packages and hidden directories
      if (EXCLUDED_PACKAGES.has(dir) || dir.startsWith('.')) {
        return false;
      }

      const mfeJsonPath = join(MFE_PACKAGES_DIR, dir, 'mfe.json');
      try {
        readFileSync(mfeJsonPath);
        return true;
      } catch {
        return false;
      }
    });

    if (mfePackages.length === 0) {
      console.log('ℹ️  No MFE packages found. Generating empty registry.');
      writeFileSync(OUTPUT_FILE, emptyRegistry());
      console.log(`\n✅ Generated ${OUTPUT_FILE}`);
      return;
    }

    console.log(`📦 Found ${mfePackages.length} MFE package(s):`);
    mfePackages.forEach((pkg) => {
      console.log(`  - ${pkg}`);
    });

    // Generate import statements
    const imports = mfePackages
      .map((pkg, idx) => {
        return `import mfe${idx} from '@/mfe_packages/${pkg}/mfe.json';`;
      })
      .join('\n');

    // Generate registry
    const registry = `export const MFE_MANIFESTS = [
${mfePackages
  .map((_, idx) => `  mfe${idx},`)
  .join('\n')}
];`;

    // Generate file content
    const content = `// AUTO-GENERATED FILE
// Generated by: scripts/generate-mfe-manifests.ts
// Do not edit manually!
// Regenerate: npm run generate:mfe-manifests

${imports}

${registry}

// Get all MFE manifests
// Allows Vite to statically analyze imports without warnings
export function getMfeManifests() {
  return MFE_MANIFESTS;
}
`;

    writeFileSync(OUTPUT_FILE, content);
    console.log(`\n✅ Generated ${OUTPUT_FILE}`);
  } catch (error) {
    console.error('❌ Error generating MFE manifests:', error);
    process.exit(1);
  }
}

function emptyRegistry(): string {
  return `// AUTO-GENERATED FILE
// Generated by: scripts/generate-mfe-manifests.ts
// Do not edit manually!
// Regenerate: npm run generate:mfe-manifests


export const MFE_MANIFESTS = [

];

// Get all MFE manifests
// Allows Vite to statically analyze imports without warnings
export function getMfeManifests() {
  return MFE_MANIFESTS;
}
`;
}

generateManifestRegistry();
