/**
 * Screen Component
 *
 * Main content area that renders the active screen.
 * Generated by `hai3 scaffold layout`.
 */

import React from 'react';

export interface ScreenProps {
  children?: React.ReactNode;
}

export const Screen: React.FC<ScreenProps> = ({ children }) => {
  return (
    <main className="flex flex-col flex-1 overflow-hidden bg-background">
      {children}
    </main>
  );
};

Screen.displayName = 'Screen';
